development:
  adapter: mysql2
  encoding: utf8
  database: dialog_rails
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: dialog_rails
  pool: 5
  username: root
  password: root
  host: localhost